version: "3"
services:
  stress:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
    command: >
      sleep 15
      && dd if=/dev/zero bs=1M | head -c 10000M | tail
    image: debian:bookworm
    restart: always