# build environment
FROM node:20.13.1-alpine as build
WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY client/package.json /app/package.json
RUN npm install --silent
RUN npm config set unsafe-perm true #https://stackoverflow.com/questions/52196518/could-not-get-uid-gid-when-building-node-docker
RUN npm install react-scripts@5.0.1 -g --silent
COPY client/ /app
RUN npm run build

# production environment
FROM nginx:1.16.0-alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]